version: '3'

services:

    dns:
        build: ./
        tty: true
        volumes:
            - ./bind/:/mnt/bind
            - ./ip.txt/:/mnt/ip.txt
        networks:
            - default
            - dns
            
    web:
        image: httpd:alpine
        ports:
            - "8080:80"
        volumes:
            - ./ip.txt/:/mnt/ip.txt
        networks:
            - default
            - web

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.200.0/24
                gateway: 192.168.200.1
    dns:
        ipv4_address: 192.168.200.11
    web:
        ipv4_address: 192.168.200.12