version: '3'

services:

    dns:
        build: ./
        tty: true
        volumes:
            - ./bind/:/mnt/bind
            - ./ip.txt/:/mnt/ip.txt
        networks:
            - default
            
    web:
        image: httpd:alpine
        ports:
            - "8080:80"
        volumes:
            - ./ip.txt/:/mnt/ip.txt
        networks:
            - default

networks:
    default:
        driver: bridge