version: '3'

services:

    dns:
        build: ./
        tty: true
        volumes:
            - ./bind/:/mnt/bind
            - ./ip.txt/:/mnt/ip.txt
        ports:
            - "53:53/udp"
        networks:
            default:
                ipv4_address: 192.168.200.11
            
    web:
        image: httpd:alpine
        ports:
            - "8080:80"
        volumes:
            - ./ip.txt/:/mnt/ip.txt
        networks:
            default:
                ipv4_address: 192.168.200.12
        dns:
            - 192.168.200.11

    ubuntu:
        image: ubuntu:20.04
        tty: true
        networks:
            default:
                ipv4_address: 192.168.200.13
        dns:
            - 192.168.200.11

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.200.0/24
